CREATE DATABASE IF NOT EXISTS css CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS css.client (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cl_name VARCHAR(100) NOT NULL,
  cl_email VARCHAR(100) NOT NULL,
  cl_phone VARCHAR(20) NOT NULL,
  cl_address VARCHAR(255) NOT NULL,
  cl_onboarded DATE NOT NULL
);
